<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title>Poslední upomínka – pokus o smír</title>
    <style>
    td { Text-align: right; }
    body { font-family: Arial; }
    </style>
</head>
<body>
{include 'poznamka.include.phtml'}
<p>Vážený zákazníku,</p>
<p>naposledy Vás tímto upozorňujeme, že jste nám doposud neuhradili následující fakturu (faktury):</p>
<table border="1" cellspacing="0" cellpadding="4" xstyle="border: 1px solid black">
<tr>
    <th>Číslo faktury</th>
    <th>Zakázka</th>
    <th>Datum vystavení</th>
    <th>Splatno</th>
    <th>Fakturováno</th>
    <th>Měna</th>
    <th>V Kč</th>
    <th>K likvidaci v Kč</th>
    <th>Po splatnosti dnů</th>
</tr>
<tr n:foreach="$reminder as $row">
    <td>{$row[cislo_faktury]}&nbsp;</td>
    <td>{$row[zakazka]}&nbsp;</td>
    <td>{$row[datum_vystaveni]}&nbsp;</td>
    <td>{$row[datum_splatnosti]}&nbsp;</td>
    <td>{$row[fakturovano]|number:2:',':' '}&nbsp;</td>
    <td>{$row[mena]}&nbsp;</td>
    <td>{$row[celkem_kc]|number:2:',':' '}&nbsp;</td>
    <td>{$row[k_likvidaci_kc]|number:2:',':' '}&nbsp;</td>
    <td>{$row[po_splatnosti]}&nbsp;</td>
</tr>
</table>
<p>Žádáme Vás o úhradu dlužné částky do 7 dnů od obdržení této upomínky a taktéž o zaslání kopie příkazu k úhradě.</p>
<p>Pokud nebude výše uvedená faktura (faktury) v tomto termínu uhrazena (uhrazeny), budeme nuceni řešit záležitost právní cestou. Tato skutečnost bude představovat navýšení dlužné částky o náklady na právní služby a úrok z prodlení.</p>
<p>Věříme, že vzhledem k předchozím obchodním vztahům nenecháte tuto kauzu dojít tak daleko a fakturu uhradíte obratem.</p>
<p>S pozdravem<br />
Prima Logistics,s.r.o.<br />
Jankovcova 1509/29<br />
170 00  Praha 7<br />
IČO:  282 39 881<br />
</p>
<p>
<strong>Kontaktní údaje:</strong><br />
Účetní oddělení:<br />
Ing. Eva Országová<br />
Finance Manager<br />
Tel: +420 734 852 202<br />
Email: finance@primalogistics.cz<br />
</p>
</body>
</html>