<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title>První upomínka</title>
    <style>
    td { Text-align: right; }
    body { font-family: Arial; }
    </style>
</head>
<body>
{include 'poznamka.include.phtml'}
<p>Vážený zákazníku,</p>
<p>při kontrole účetních dokladů jsme zjistili, že nám doposud nebyly uhrazeny následující faktury, které jsou po splatnosti:</p>
<table border="1" cellspacing="0" cellpadding="4" xstyle="border: 1px solid black">
<tr>
    <th>Číslo faktury</th>
    <th>Zakázka</th>
    <th>Datum vystavení</th>
    <th>Splatno</th>
    <th>Fakturováno</th>
    <th>Měna</th>
    <th>V Kč</th>
    <th>K likvidaci v Kč</th>
    <th>Po splatnosti dnů</th>
</tr>
<tr n:foreach="$reminder as $row">
    <td>{$row[cislo_faktury]}&nbsp;</td>
    <td>{$row[zakazka]}&nbsp;</td>
    <td>{$row[datum_vystaveni]}&nbsp;</td>
    <td>{$row[datum_splatnosti]}&nbsp;</td>
    <td>{$row[fakturovano]|number:2:',':' '}&nbsp;</td>
    <td>{$row[mena]}&nbsp;</td>
    <td>{$row[celkem_kc]|number:2:',':' '}&nbsp;</td>
    <td>{$row[k_likvidaci_kc]|number:2:',':' '}&nbsp;</td>
    <td>{$row[po_splatnosti]}&nbsp;</td>
</tr>
</table>
<p>Věříme, že se jedná pouze o nedorozumění a žádáme o úhradu v co nejbližším termínu. Pokud již byla platba uskutečněna, berte prosím tuto upomínku jako bezpředmětnou.</p>
<p>S pozdravem<br />
Prima Logistics,s.r.o.<br />
Jankovcova 1509/29<br />
170 00  Praha 7<br />
IČO:  282 39 881<br />
</p>
<p>
<strong>Kontaktní údaje:</strong><br />
Účetní oddělení:<br />
Ing. Eva Országová<br />
Finance Manager<br />
Tel: +420 734 852 202<br />
Email: finance@primalogistics.cz<br />
</p>
</body>
</html>