<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title>Druhá upomínka uhrazení faktury / Second reminder for overdue invoice</title>
    <style>
    td { Text-align: right; }
    body { font-family: Arial; }
    </style>
</head>
<body>
{include 'poznamka.include.phtml'}
<p>Vážený zákazníku,</p>
<p>i přes první upomínku jsme od Vás doposud neobdrželi platbu za následující fakturu (faktury):</p>
<table border="1" cellspacing="0" cellpadding="4" xstyle="border: 1px solid black">
<tr>
    <th>Číslo faktury</th>
    <th>Zakázka</th>
    <th>Datum vystavení</th>
    <th>Splatno</th>
    <th>Fakturováno</th>
    <th>Měna</th>
    <th>V Kč</th>
    <th>K likvidaci v Kč</th>
    <th>Po splatnosti dnů</th>
</tr>
<tr n:foreach="$reminder as $row">
    <td>{$row[cislo_faktury]}&nbsp;</td>
    <td>{$row[zakazka]}&nbsp;</td>
    <td>{$row[datum_vystaveni]}&nbsp;</td>
    <td>{$row[datum_splatnosti]}&nbsp;</td>
    <td>{$row[fakturovano]|number:2:',':' '}&nbsp;</td>
    <td>{$row[mena]}&nbsp;</td>
    <td>{$row[celkem_kc]|number:2:',':' '}&nbsp;</td>
    <td>{$row[k_likvidaci_kc]|number:2:',':' '}&nbsp;</td>
    <td>{$row[po_splatnosti]}&nbsp;</td>
</tr>
</table>
<p>Žádáme Vás tímto o uhrazení dlužné částky nejpozději do sedmi kalendářních dnů.</p>
<p>Pokud do stanovené doby faktury neuhradíte, budeme nuceni dlužnou částku vymáhat soudní cestou.</p>
<p>Dále upozorňujeme, že Vám vyúčtujeme náklady na vymáhání pohledávky* a úrok z prodlení**, pokud nebude platba připsána na náš účet nejpozději 28. den po splatnosti.</p>
<p>* Náklady na vymáhání pohledávky dle nařízení vlády č. 351/2013 Sb. ve výši 1 200,&ndash; Kč.<br />
**Úrok z prodlení v zákonné výši podle nařízení vlády č. 351/2013 Sb. ve výši repo sazby stanovené Českou národní bankou pro první den kalendářního pololetí, v němž došlo k prodlení, zvýšené o 8 procentních bodů.</p>
<p>S pozdravem<br />
Prima Warehousing and Distribution s.r.o. <br />
U Prioru 1076/5<br />
161 00  Praha 6<br />
IČ: 243 11 111<br />
</p>
<p>
<strong>Kontaktní údaje:</strong><br />
Kateřina Bartošová<br />
Senior Accountant<br />
Email: uctarna@primawad.cz<br />
</p>

<br />

<p>Dear customer.</p>
<p>Despite the first reminder, we have still not received a remittance following invoice(s):</p>
<table border="1" cellspacing="0" cellpadding="4" xstyle="border: 1px solid black">
<tr>
    <th>Invoice number</th>
    <th>Contract</th>
    <th>Date of issue</th>
    <th>Due date</th>
    <th>Invoiced amount</th>
    <th>Currency</th>
    <th>In CZK</th>
    <th>Total due</th>
    <th>Overdue days</th>
</tr>
<tr n:foreach="$reminder as $row">
    <td>{$row[cislo_faktury]}&nbsp;</td>
    <td>{$row[zakazka]}&nbsp;</td>
    <td>{$row[datum_vystaveni]}&nbsp;</td>
    <td>{$row[datum_splatnosti]}&nbsp;</td>
    <td>{$row[fakturovano]|number:2:'.':','}&nbsp;</td>
    <td>{$row[mena]}&nbsp;</td>
    <td>{$row[celkem_kc]|number:2:'.':','}&nbsp;</td>
    <td>{$row[k_likvidaci_kc]|number:2:'.':','}&nbsp;</td>
    <td>{$row[po_splatnosti]}&nbsp;</td>
</tr>
</table>
<p>We ask you for this outstanding amount to be paid within seven calendar days.</p>
<p>If you do not pay the invoice within the stipulated time, we will be forced to recover the amount owed through the courts.</p>
<p>Please note that we will charge you the recovery costs* and interest**, unless the payment is credited to out account no later than 28 days after the due date</p>
<p> * The cost of recovery according to Government Order no. 351/2013 Coll. in the amount of CZK 1,200.&ndash;.<br />
** The default interest at the statutory rate based on Government Order no. 351/2013 Coll., the repo rate set by the Czech National Bank for the first day of the calendar half-year in which the default occurred, increased by 8 percentage points.</p>
<p>Sincerely<br />
Prima Warehousing and Distribution s.r.o. <br />
U Prioru 1076/5<br />
161 00  Praha 6<br />
Czech Republic<br />
VAT no: 243 11 111<br />
</p>
<p>
<strong>Contact information:</strong><br />
Katerina Bartosova<br />
Senior Accountant<br />
Email: uctarna@primawad.cz<br />
</p>
</body>
</html>