<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title>Poslední upomínka - pokus o smír / Last reminder for overdue invoice</title>
    <style>
    td { Text-align: right; }
    body { font-family: Arial; }
    </style>
</head>
<body>
{include 'poznamka.include.phtml'}
{include 'upominka3_cz_body.phtml'}

<p>S pozdravem<br />
Prima Warehousing and Distribution s.r.o. <br />
U Prioru 1076/5<br />
161 00  Praha 6<br />
IČ: 243 11 111<br />
</p>
<p>
<strong>Kontaktní údaje:</strong><br />
Kateřina Bartošová<br />
Senior Accountant<br />
Email: uctarna@primawad.cz<br />
</p>

<br />

{include 'upominka3_en_body.phtml'}

<p>Sincerely<br />
Prima Warehousing and Distribution s.r.o. <br />
U Prioru 1076/5<br />
161 00  Praha 6<br />
Czech Republic<br />
VAT no: 243 11 111<br />
</p>
<p>
<strong>Contact information:</strong><br />
Katerina Bartosova<br />
Senior Accountant<br />
Email: uctarna@primawad.cz<br />
</p>
</body>
</html>