ALTER TABLE Nabidka ADD FCL1 int SPARSE NULL;
ALTER TABLE Nabidka ADD FCL2 int SPARSE NULL;
ALTER TABLE Nabidka ADD FCL3 int SPARSE NULL;
ALTER TABLE Nabidka ADD FCL4 int SPARSE NULL;
ALTER TABLE Nabidka ADD Agent1 nvarchar(50) SPARSE NULL;
ALTER TABLE Nabidka ADD Zasilka nvarchar(50) SPARSE NULL;
GO

ALTER TABLE Nabidka WITH CHECK ADD CONSTRAINT FK_Nabidka_TypKontejneru1
    FOREIGN KEY ( FCL1 ) REFERENCES TypKontejneru ( ID );-- ON DELETE CASCADE;
ALTER TABLE Nabidka WITH CHECK ADD CONSTRAINT FK_Nabidka_TypKontejneru2
    FOREIGN KEY ( FCL2 ) REFERENCES TypKontejneru ( ID );-- ON DELETE CASCADE;
ALTER TABLE Nabidka WITH CHECK ADD CONSTRAINT FK_Nabidka_TypKontejneru3
    FOREIGN KEY ( FCL3 ) REFERENCES TypKontejneru ( ID );-- ON DELETE CASCADE;
ALTER TABLE Nabidka WITH CHECK ADD CONSTRAINT FK_Nabidka_TypKontejneru4
    FOREIGN KEY ( FCL4 ) REFERENCES TypKontejneru ( ID );-- ON DELETE CASCADE;
