BEGIN TRANSACTION
CREATE TABLE Staty (
[N3] smallint NOT NULL,
[A2] char(2) NOT NULL,
[A3] char(3) NOT NULL,
[PlnyNazevC] nvarchar(255) NOT NULL,
[ZkracenyNazevC] nvarchar(255) NOT NULL,
[PlnyNazevA] nvarchar(255) NOT NULL,
[ZkracenyNazevA] nvarchar(255) NOT NULL
)
GO

ALTER TABLE Staty ADD CONSTRAINT
	PK_Staty PRIMARY KEY CLUSTERED 
	(
	N3
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
COMMIT
