IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'Nastaveni') AND type in (N'U'))
    DROP TABLE Nastaveni;

CREATE TABLE Nastaveni
	(
	NAME varchar(50) NOT NULL,
	VALUE varchar(50) NOT NULL
	)  ON [PRIMARY]
GO
ALTER TABLE Nastaveni ADD CONSTRAINT
	PK_Nastaveni PRIMARY KEY CLUSTERED 
	(
	NAME
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
-- COMMIT