Begin Tran
ALTER TABLE Preprava ADD MimoEU bit;
GO
UPDATE Preprava SET MimoEU=0;
UPDATE Preprava SET MimoEU=1 WHERE DPH=0;
ALTER TABLE Preprava DROP COLUMN DPH;
GO
ALTER TABLE Preprava ALTER COLUMN MimoEU bit NOT NULL;
ALTER TABLE Preprava ADD CONSTRAINT DF_Preprava_MimoEU DEFAULT 0 FOR MimoEU;
GO

ALTER TABLE PrepravaSil ADD MimoEU bit;
GO
UPDATE PrepravaSil SET MimoEU=0;
UPDATE PrepravaSil SET MimoEU=1 WHERE DPH=0;
ALTER TABLE PrepravaSil DROP COLUMN DPH;
GO
ALTER TABLE PrepravaSil ALTER COLUMN MimoEU bit NOT NULL;
ALTER TABLE PrepravaSil ADD CONSTRAINT DF_PrepravaSil_MimoEU DEFAULT 0 FOR MimoEU;
GO


COMMIT
--ROLLBACK