ALTER TABLE Firma ADD Zalozil nvarchar(100) NULL;
ALTER TABLE Firma ADD ZalozilCas datetime NULL;

ALTER TABLE Firma ADD CONSTRAINT DF_Firma_Zalozil DEFAULT SUSER_NAME() FOR Zalozil;
ALTER TABLE Firma ADD CONSTRAINT DF_Firma_ZalozilCas DEFAULT CURRENT_TIMESTAMP FOR ZalozilCas;
